commerce_payment.commerce_payment_gateway.commerce_icepay:
  type: commerce_payment_gateway_configuration
  mapping:
    icepay_merchant_id:
      type: string
      label: 'Merchant ID'
    icepay_secret_code:
      type: string
      label: 'Secret Key'
